# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Date:yyyyMMdd)$(Rev:.r)


variables:
  - name: TF_VAR_app_name
    value: "kfsolapp"
  - name: vmImageName
    value: "ubuntu-latest"
  - name: TF_VAR_region
    value: "us-east-1"
  - name: AWS_REGION
    value: "us-east-1"
  - name: BRANCH_NAME
    value: "dev"    
trigger:
- dev

pool:

  vmImage: 'ubuntu-latest'

#container: ubuntu:16.04 # container to run this job inside of

# steps:

# - script: printenv44


# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

jobs:
- template: 'createsubdir/azure-pipelines.yml'
  parameters:
    TF_VAR_app_name: $(TF_VAR_app_name)
    BRANCH_NAME: $(BRANCH_NAME)

- template: 'createsubdir/azure-pipelines.yml'
  parameters:
    TF_VAR_app_name: $(TF_VAR_app_name)
    BRANCH_NAME: $(BRANCH_NAME)    
# - template: 'django-multi-environment/azure-pipelines.yml'
# - template: 'flask-basic/azure-pipelines.yml'
# - template: 'library-basic/azure-pipelines.yml'
# - template: 'library-flit/azure-pipelines.yml'
