# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Date:yyyyMMdd)$(Rev:.r)


variables:
  - name: TF_VAR_app_name
    value: "kfsolapp"
  - name: vmImageName
    value: "ubuntu-latest"
  - name: TF_VAR_region
    value: "us-east-1"
  - name: AWS_REGION
    value: "us-east-1"
  - name: BRANCH_NAME
    value: "dev"
  - name: ADOBRANCHNAME
    value: Build.SourceBranchName
trigger:
- dev

pool:

  vmImage: 'ubuntu-latest'

# jobs:
# - template: 'preps/azure-pipelines.yml'
#   parameters:
#     TF_VAR_app_name: $(TF_VAR_app_name)
#     BRANCH_NAME: $(BRANCH_NAME)


steps:
  # -
  # - Prerequisites
  # -
  - script: |
      echo branch name is $ADOBRANCHNAME
    displayName: adobranchname
