# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: name  # defaults for any parameters that aren't specified
    default: ''
  - name: vmImage
    default: ''
  

variables:
  - name: TF_VAR_app_name
    value: "kfsolapp"
  - name: vmImageName
    value: "ubuntu-latest"
  - name: TF_VAR_region
    value: "us-east-1"
  - name: AWS_REGION
    value: "us-east-1"
  - name: BRANCH_NAME
    value: $(Build.SourceBranchName)

trigger:
- dev

pool:

  vmImage: 'ubuntu-latest'

# steps:
#   - script: |
#       echo branch name is $BRANCH_NAME and is derived from Azure Devops Predefine Variable
#     displayName: branchname

    
jobs:
- job: DoIt
  steps:
  - script: echo npm install
  - script: echo npm test  
  - bash: |  
      echo branch name is $BRANCH_NAME and is derived from Azure Devops Predefine Variable
  displayName: Show_branch_name
- template: 'preps/azure-pipelines.yml'
  parameters:
    TF_VAR_app_name: $(TF_VAR_app_name)
    BRANCH_NAME: $(BRANCH_NAME)
