# - run:
#   name: prepare-files-folders
#   command: |
#     ./scripts/prepare-files-folders.sh
# name: $(Date:yyyyMMdd)$(Rev:.r)
# variables:
#   - name: TF_VAR_app_name
#     value: "kfsolapp"
#   - name: vmImageName
#     value: "ubuntu-latest"
#   - name: TF_VAR_region
#     value: "us-east-1"
#   - name: AWS_REGION
#     value: "us-east-1"
jobs:
  - job: 'preparefolder'
    displayName: job-prepare-files-folders
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        cd createsubdir/scripts
        export TF_VAR_app_name=${{parameters.TF_VAR_app_name}}
        export BRANCH_NAME=${{parameters.BRANCH_NAME}}
        echo TF_VAR_app_name=$TF_VAR_app_name
        ./prepare-files-folders.sh
      displayName: 'script-prepare-files-folders'    
    - script: |
        cd preparebackend/scripts
        export TF_VAR_app_name=${{parameters.TF_VAR_app_name}}
        export BRANCH_NAME=${{parameters.BRANCH_NAME}}
        echo TF_VAR_app_name=$TF_VAR_app_name
        ./prepare-backend.sh
      displayName: 'script-prepare-backend'