jobs:
  - job: 'preparefolder'
    displayName: job-prepare-files-folders
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        cd preps
        export TF_VAR_app_name=${{parameters.TF_VAR_app_name}}
        export BRANCH_NAME=${{parameters.BRANCH_NAME}}
        echo TF_VAR_app_name=$TF_VAR_app_name
        ./prepare-files-folders.sh
      displayName: 'script-prepare-files-folders'    
    - script: |
        cd preps
        export TF_VAR_app_name=${{parameters.TF_VAR_app_name}}
        export BRANCH_NAME=${{parameters.BRANCH_NAME}}
        echo TF_VAR_app_name=$TF_VAR_app_name
        ./prepare-backend.sh
      displayName: 'script-prepare-backend'